Movies/Controllers/MovieController.cs
using System;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Movies.BLL.Infrastructure;
using Movies.Models;

namespace Movies.Controllers
{
    public class MovieController : Controller
    {
        readonly IService<MovieModel> _service;

        public MovieController(IService<MovieModel> service)
        {
            _service = service;
        }

        // GET: Movie
        public ActionResult Index(int page = 1)
        {
            return View(_service.GetAll(page));
        }

        // GET: Movie/Details/5
        public ActionResult Details(int id)
        {
            return View(_service.Get(id));
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        [HttpPost]
        public ActionResult Create(MovieModel movie)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _service.Create(movie);

                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    throw new HttpException(e.Message);
                }
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Movie/Edit/5
        public ActionResult Edit(int id)
        {
            MovieModel movie = _service.Get(id);
            if (System.Web.HttpContext.Current.User.Identity.GetUserId() == movie.UserId)
            {
                return View(_service.Get(id));
            }

            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        // POST: Movie/Edit/5
        [HttpPost]
        public ActionResult Edit(MovieModel movie)
        {
            try
            {
                _service.Update(movie);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw new HttpException(e.Message);
            }
        }

        // GET: Movie/Delete/5
        public ActionResult Delete(int id)
        {
            return View(_service.Get(id));
        }

        // POST: Movie/Delete/5
        [HttpPost]
        public ActionResult DeleteItem(int id)
        {
            try
            {
                _service.Delete(id);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                throw new HttpException(e.Message);
            }
        }
    }
}

Movies/Views/Movie/Create.cshtml
@model Movies.Models.MovieModel

@{
    ViewBag.Title = "Create";
}

<h2>Добавить фильм</h2>


@using (Html.BeginForm("Create", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MovieModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageFile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductionYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductionYear, new { htmlAttributes = new { @class = "form-control", min = 1900, max = DateTime.Now.Year } })
                @Html.ValidationMessageFor(model => model.ProductionYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DirectorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DirectorName, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                @Html.ValidationMessageFor(model => model.DirectorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies/Views/Movie/Delete.cshtml
@model Movies.Models.MovieModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductionYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductionYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DirectorName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DirectorName)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteItem", "Movie", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="hidden" value="@Model.Id" name="id" />
            <input type="submit" value="Delete" name="id" class="btn btn-default"/> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Movies/Views/Movie/Details.cshtml
@using Microsoft.AspNet.Identity
@model Movies.Models.MovieModel

@{
    ViewBag.Title = "Details";
}
<div class="container">
    <div class="row">
        <div class="jumbotron col">
            <h6><b>@Html.DisplayNameFor(model => model.ProductionYear)</b>: @Html.DisplayFor(model => model.ProductionYear)</h6>
            <h1>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h1>
            <p class="lead"><b>@Html.DisplayNameFor(model => model.DirectorName)</b> : @Html.DisplayFor(model => model.DirectorName)</p>
            <hr class="my-4">
            <p><b>@Html.DisplayNameFor(model => model.Description)</b> : @Html.DisplayFor(model => model.Description)</p>
            <p>
                @if (User.Identity.GetUserId() == Model.UserId)
                {
                    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}, new {@class = "btn btn-primary"})
                }

                @Html.ActionLink("Back to List", "Index", new {area = ""}, new {@class = "btn btn-primary"})
            </p>
        </div>
        <div class="col">
            <img width="200" class="align-content-lg-end" src="@Model.ImagePath"/>
        </div>
    </div>
</div>

Movies/Views/Movie/Edit.cshtml
@model Movies.Models.MovieModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ImageFile, new { type = "file" })
                @Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductionYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductionYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductionYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DirectorName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DirectorName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DirectorName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Movies/Views/Movie/Index.cshtml
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Bootstrap4
@model X.PagedList.IPagedList<Movies.Models.MovieModel>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <h2>Главная</h2>

    @if (User.Identity.IsAuthenticated)
    {
        <p>
            @Html.ActionLink("Create New", "Create", new { @class = "btn btn-primary" })
        </p>
    }
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@item.ImagePath" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">@item.Description</p>
                        <p class="card-text">@item.ProductionYear</p>
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }
    </div>
    <hr/>
    <div class="row">
        <div class="align-content-around">
            @Html.PagedListPager(Model, page => Url.Action("Index", new {page}), Bootstrap4PagedListRenderOptions.ClassicPlusFirstAndLast)
        </div>
    </div>

</div>